import Head from 'next/head'
import {HomePage} from "@/pages(notNEXT)/api/Components";
import Test from "@/pages(notNEXT)/TEST";
export default function Home() {
  return (
    <>
      <Head>
        <title>Sportamin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Test/>
{/*
      <HomePage/>
*/}
    </>
  )
}
export async function getServerSideProps(context) {
    console.log(context);
    return {
        props: {

        }
    }
}
